{
 "title": "Vehicle Data",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Vehicle Locations",
   "type": "geomap",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(vehicle_data_latitude{field=\"Location\"}) by (vin)",
     "legendFormat": "{{vin}} LocationLatitude"
    },
    {
     "expr": "avg(vehicle_data_longitude{field=\"Location\"}) by (vin)",
     "legendFormat": "{{vin}} LocationLongitude"
    },
    {
     "expr": "avg(vehicle_data_latitude{field=\"DestinationLocation\"}) by (vin)",
     "legendFormat": "{{vin}} DestinationLocationLatitude"
    },
    {
     "expr": "avg(vehicle_data_longitude{field=\"DestinationLocation\"}) by (vin)",
     "legendFormat": "{{vin}} DestinationLocationLongitude"
    }
   ]
  },
  {
   "title": "List of VIN's",
   "type": "table",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "group by (vin) (vehicle_data)", "legendFormat": "{{vin}}" }
   ]
  },
  {
   "title": "Odometer",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthmi" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vehicle_data{field=\"Odometer\"}) by (vin)",
     "legendFormat": "{{vin}} Odometer"
    }
   ]
  },
  {
   "title": "Battery Level",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vehicle_data{field=\"BatteryLevel\"}) by (vin)",
     "legendFormat": "{{vin}} Battery Level"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "avg(vehicle_data{field=\"PackCurrent\"}) by (vin)",
     "legendFormat": "{{vin}} Current"
    },
    {
     "expr": "avg(vehicle_data{field=\"PackVoltage\"}) by (vin)",
     "legendFormat": "{{vin}} Voltage"
    }
   ]
  },
  {
   "title": "EstBatteryRange",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "avg(vehicle_data{field=\"EstBatteryRange\"}) by (vin)",
     "legendFormat": "{{vin}} EstBatteryRange"
    }
   ]
  },
  {
   "title": "Temperature Readings (Inside & Outside)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "((avg(vehicle_data{field=\"InsideTemp\"}) by (vin)) * 9 / 5) + 32",
     "legendFormat": "{{vin}} Inside Temp"
    },
    {
     "expr": "((avg(vehicle_data{field=\"OutsideTemp\"}) by (vin)) * 9 / 5) + 32",
     "legendFormat": "{{vin}} Outside Temp"
    }
   ]
  },
  {
   "title": "VehicleSpeed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "avg(vehicle_data{field=\"VehicleSpeed\"}) by (vin)",
     "legendFormat": "{{vin}} VehicleSpeed"
    }
   ]
  },
  {
   "title": "Gear",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(vehicle_data{field=\"Gear\"}) by (vin)",
     "legendFormat": "{{vin}} Gear"
    }
   ]
  },
  {
   "title": "TimeToFullCharge",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(vehicle_data{field=\"TimeToFullCharge\"}) by (vin)",
     "legendFormat": "{{vin}} TimeToFullCharge"
    }
   ]
  }
 ]
}