apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fleet-manager
  labels:
    app: fleet-manager
spec:
  selector:
    matchLabels:
      app: fleet-manager
  namespaceSelector:
    any: true
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s