apiVersion: v1
kind: Service
metadata:
  name: fleet-manager
  labels:
    app: fleet-manager
spec:
  selector:
    app: fleet-manager
  ports:
    - name: metrics
      port: 2112
      targetPort: 2112
      protocol: TCP